const test=require('node:test')
const assert=require('node:assert/strict')
const {ROOT,inside,search,validate}=require('./asset-library.cjs')
const {compose,checkText}=require('./compose-figures.cjs')
const scene=()=>({schemaVersion:1,style:'workshop-pastel-v1',width:1200,height:740,question:'谁负责想？',description:'大脑图',boundary:'比喻不是事实等式',claims:['L01-C01'],elements:[{type:'object',asset:'model-brain-v1',x:100,y:120,width:240,height:240}]})
test('registered native assets validate',()=>assert.equal(validate().assets,11))
test('search Chinese, English and combined aliases',()=>{assert.equal(search('大脑')[0].id,'model-brain-v1');assert.equal(search('MODEL')[0].id,'model-brain-v1');assert.equal(search('工作 日志')[0].id,'session-journal-v1');assert.equal(search('不存在的独角兽').length,0)})
test('reject asset path escape and absolute paths',()=>{assert.throws(()=>inside(ROOT,'../private.txt'),/escaped/);assert.throws(()=>inside(ROOT,ROOT),/Absolute/)})
test('deterministic reuse without mutating recipe',()=>{const s=scene(),before=JSON.stringify(s);assert.equal(compose(s),compose(s));assert.equal(JSON.stringify(s),before);assert.match(compose(s),/data-asset="model-brain-v1"/)})
test('missing asset is an error, never silently redraw',()=>{const s=scene();s.elements[0].asset='unknown-v1';assert.throws(()=>compose(s),/Unknown asset/)})
test('same object twice has unique embedded IDs',()=>{const s=scene();s.elements.push({...s.elements[0],x:500});const ids=[...compose(s).matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length)})
test('composition retains transparent fill inheritance on imported paths',()=>assert.match(compose(scene()),/<svg data-asset="model-brain-v1"[^>]*fill="none"/))
test('objects must stay within canvas',()=>{const s=scene();s.elements[0].x=1150;assert.throws(()=>compose(s),/out of bounds/)})
test('arrows must declare their meaning; optional path is dashed',()=>{const s=scene();s.elements.push({type:'arrow',x:0,y:0,x2:10,y2:10});assert.throws(()=>compose(s),/semantic meaning/);s.elements[1].meaning='optional tool request';s.elements[1].optional=true;assert.match(compose(s),/stroke-dasharray="7 7"/)})
test('missing handwriting glyph cannot silently fall back in a figure',()=>{assert.throws(()=>checkText('大脑',new Set([22823])),/missing glyphs/);checkText('大脑',new Set([22823,33041]))})
test('text escapes XML and rejects unsafe colors',()=>{const s=scene();s.elements.push({type:'text',x:30,y:30,text:'<script>&',size:28});assert.match(compose(s),/&lt;script&gt;&amp;/);s.elements[1].color='url(https://invalid)';assert.throws(()=>compose(s),/Invalid text color/)})
