#!/usr/bin/env node
const fs=require('node:fs')
const path=require('node:path')
const {marked}=require('marked')
const {ROOT}=require('./asset-library.cjs')
const {checkText}=require('./compose-figures.cjs')
const {validateSite}=require('./check-site.cjs')
const out=path.join(ROOT,'output/site')
// Only this disposable, fixed build directory may be cleared. Never follow links.
for(const dir of [path.join(ROOT,'output'),out])if(fs.existsSync(dir)&&fs.lstatSync(dir).isSymbolicLink())throw new Error(`Refusing linked output: ${dir}`)
if(path.relative(ROOT,out)!==path.join('output','site'))throw new Error('Unexpected site output')
fs.rmSync(out,{recursive:true,force:true})
function write(file,text){const target=path.join(out,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text)}
function copy(file,target=file){const source=path.join(ROOT,file);if(!fs.lstatSync(source).isFile())throw new Error(`Not a regular file: ${file}`);write(target,fs.readFileSync(source))}
const coverage=new Set(JSON.parse(fs.readFileSync(path.join(ROOT,'assets/fonts/provenance.json'),'utf8')).codepoints)
const home=fs.readFileSync(path.join(ROOT,'site/index.html'),'utf8')
checkText(home.replace(/<[^>]*>/g,''),coverage)
write('index.html',home)
copy('site/site.css','site.css')
write('.nojekyll','')
for(const file of ['workshop-hand.woff2','OFL.txt','provenance.json'])copy(`assets/fonts/${file}`)
for(const file of ['catalog.json','style.json'])copy(`assets/library/${file}`)
const catalog=JSON.parse(fs.readFileSync(path.join(ROOT,'assets/library/catalog.json'),'utf8'))
for(const item of catalog.assets)copy(`assets/library/${item.file}`)
for(const name of fs.readdirSync(path.join(ROOT,'assets/lesson-01/v2')).filter(n=>n.endsWith('.svg')))copy(`assets/lesson-01/v2/${name}`)
let lesson=fs.readFileSync(path.join(ROOT,'previews/lesson-01.html'),'utf8')
lesson=lesson.replace(/\s*<base href="[^"]*">/,'').replaceAll('../production/lesson-01/lesson-01-source-facts.md','../evidence.html')
lesson=lesson.replace('<nav aria-label="教材文档导航">','<nav aria-label="教材文档导航"><a href="../index.html">← 阅读首页</a>')
write('previews/lesson-01.html',lesson)
let gallery=fs.readFileSync(path.join(ROOT,'assets/library/index.html'),'utf8')
gallery=gallery.replace('<main>','<main><a href="../../index.html">← 阅读首页</a>')
write('assets/library/index.html',gallery)
const facts=fs.readFileSync(path.join(ROOT,'production/lesson-01/lesson-01-source-facts.md'),'utf8')
checkText(facts,coverage)
const style=lesson.match(/<style>([\s\S]*?)<\/style>/)[1].replaceAll('../assets/','assets/')
write('evidence.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>第一讲 · 源码事实矩阵</title><link rel="icon" href="data:,"><style>${style}</style><nav><a href="index.html">← 阅读首页</a><a href="previews/lesson-01.html">第一讲</a></nav><main><article>${marked.parse(facts)}</article></main></html>`)
console.log(validateSite(out))
